### ISSUE TITLE
Example tasks list in issue

### ISSUE THREAD

**Issue by wanderingmaxim** [wanderingmaxim/introduction-to-github#2]
- [x] [Learn how to create issues](https://github.com/wanderingmaxim/introduction-to-github/issues/1)
- [x] [Learn how to close issues](https://github.com/wanderingmaxim/introduction-to-github/issues/1)
- [ ] [Learn how to create tasks lists](https://github.com/wanderingmaxim/introduction-to-github/issues/2#issue-1650492846)
